services:
  - type: web
    name: kitsune-py
    env: python
    buildCommand: |
      sudo apt-get update && sudo apt-get install -y python3-dev python3-pip build-essential libjpeg-dev zlib1g-dev libpng-dev
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: ./start.sh
